//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAssignments.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class EmployeesTable
    {
        public string EmpName { get; set; }
        public System.DateTime EntryDate { get; set; }

        [DataType(DataType.Date)]
        public System.DateTime EmployementDate { get; set; }
        public decimal salary { get; set; }
        public int age { get; set; }

        [DisplayName("Are You Vaccinated?")]
        public int VaxOrNot { get; set; }
        public string Position { get; set; }
        public string admin { get; set; }
        public int isComplete { get; set; }
        public string password { get; set; }
    }
}
