//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAssignments.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EmployeTable
    {
        [Key]
        public string EmpName { get; set; }
        public System.DateTime EntryDate { get; set; }
        public System.DateTime EmployementDate { get; set; }
        public decimal Salary { get; set; }
        public Nullable<int> VaxOrNot { get; set; }
        public Nullable<int> Age { get; set; }
        public string Position { get; set; }
        public string Admin { get; set; }
        public string Password { get; set; }
    }
}
