//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAssignments.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Project
    {
        public string EmpName { get; set; }
        public string ProjectName { get; set; }
        public string ProjectManager { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime ProjectStartDate { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime ProjectEndDate { get; set; }
        public string Department { get; set; }
        public string Admin { get; set; }
        public int isComplete { get; set; }
        public int projectis { get; set; }
    }
}
